#!/usr/bin/perl

while( defined($packagefile = glob("/var/lib/dpkg/alternatives/*")) )
{
    $package = "$1" if $packagefile =~ m#^.*/([^/]*)$#;

    open( FILE, $packagefile ) || die( "Couldn't open $packagefile\n" );
    
    $_ = <FILE>;  # auto 
    $_ = $package;

    @provides = ();
    $cnt = 0;
    do {
	$alt = "/etc/alternatives/" . $_;
	
	$_ = <FILE>; chomp($_);
	$altredir = $_;
	
	push @provides, $altredir;
	
	$cnt = $cnt + 1;
	
	$_ = <FILE>; chomp($_);
    } while( $_ ne "" );	
    
    while( $main = <FILE> ) {
	chomp($main);
	unless ( $main eq "" ) {
	    $pri = <FILE>; chomp($pri);
            print "========== $main\n";
            print $provides[0], "\n";
	    for ( $i = 1; $i < $cnt; $i++ ) { 
		$alt = <FILE>; chomp($alt);
		print $provides[$i], "\n" unless ( $alt eq "" );
                print "--------\n";
	    }
	}
    }    
}
