#!/usr/bin/perl -wn
BEGIN{
	require '/usr/lib/cruft/common.pl';
	sub is_subdir($$);
	sub ignores;
	sub scan_fs;
	sub all_fs;
	sub noscan_fs;
	sub get_direct_fs($@);
	sub prunes($@);
	@I=ignores;@S=scan_fs;@NS=noscan_fs;
	%M  = ( map {$_=> 1} @S);
	%M  = ( %M, map {$_=>0} @NS );
}

chomp;
$l=$_;
next if grep { is_subdir($_,$l) } @I;
print "$l\n" or die $! if $M{get_direct_fs($l,(@S,@NS))};

END {
	close STDOUT or die $!;
}

