#!/bin/dash
# Read standard input and filter out files which match filter patterns listed
# in the file given as the first argument
set -e
. /usr/lib/cruft/common_legacy.sh
cruft_debug 2

list="$1"
exec /usr/lib/cruft/filter_shell $(cat $list)

