#!/bin/dash
set -e
[ -f ../Makefile ] || ( cd .. && ./configure )
[ -x ../merge_diff_test ] || make -C .. merge_diff_test  CFLAGS="-g -O0 -Wall -W -ansi -pedantic-errors"
set +e
for subdir in [0-9][0-9]
do
	echo "ENTERING ${subdir}"
	cd ${subdir}
	outs="$(cd output && echo *)"
	rm -f ${outs}
	mkdir -p run
	cp input/* run
	#gdb ../../merge_diff_test run
	../../merge_diff_test run
	for out in $outs
	do
		diff -u output/${out} run/${out}
	done
	cd ..
done

