#!/bin/sh
[ -d /etc/ssl/certs ] || exit 0

find /etc/ssl/certs -type l -name \*.pem | 
 while read name
 do
   [ -e "$name" ] && echo "$name"
 done

find /etc/ssl/certs -type l -name '????????.?' |
 while read name
 do
   [ -e "$name" ] && echo "$name"
 done
