#!/bin/sh
# If cruft is not entering /dev, then don't scan it here either
if mount | awk '$3 == "/dev" {print $1}' | egrep -q '^(proc|(a|n|usb|tmp|sys)fs|devpts)$'
then
	exit 0
else
: #	find /dev
# XXX maybe get a list from makedev?
fi
