#!/bin/dash
# If cruft is not entering /dev, then don't scan it here either
if mount | awk '$3 == "/dev" {print $1}' | egrep -q '^(proc|devpts|nfs[1234]?|ncp|coda|(a|smb|ci|ncp|usb|tmp|sys)fs)$'
then
	exit 0
else
: #	find /dev
# XXX maybe get a list from makedev?
fi
