#!/bin/sh -e

. /usr/lib/cruft/common.sh
cruft_debug

for package in $(/usr/sbin/dkms status | cut -f1 -d\, | sort -u)
do
	if [ -d "/var/lib/dkms/$package" ]
	then
		cruft_find "/var/lib/dkms/$package"
	fi
done
