#!/bin/sh
test -d /usr/share/gconf/schemas || exit 0
find /usr/share/gconf/schemas -type f | xargs -r egrep '<(applyto|key)>' |
 perl -n -e 'm{<\w+>(/[^/]+/[^/<]+)};print $1."\n"' | sort -u |
 while read n
 do
   find /etc/gconf/gconf.xml.defaults$n
 done

