#!/bin/dash
echo /boot/grub/locale
dpkg-query -L grub-common | grep 'grub\.mo' | sed 's#usr/share#boot/grub#' | sed 's#/LC_MESSAGES/grub##'
[ -e /usr/share/grub/unicode.pf2 ] && echo /boot/grub/fonts/unicode.pf2

