#!/bin/bash
d=/boot/grub
if [ ! -d "$d" ]; then d=/boot/boot/grub; fi
if [ ! -f "$d" ]; then exit 0; fi
find $d -type f -name stage1 -or -name stage2 -or -name \*_stage1_5 -or -name device.map -or -name menu.lst\*
