#!/bin/sh -e
ver=$(uname -r)
if [ -e /lib/modules/${ver}/updates/dkms/kdbus.ko ]
then
    echo /lib/modules/${ver}/updates
    echo /lib/modules/${ver}/updates/dkms
    echo /lib/modules/${ver}/updates/dkms/kdbus.ko
fi
