#!/bin/dash

set -e
. /usr/lib/cruft/common.sh
cruft_debug

mount | egrep ".* on .* type ext[234]" | awk '{ print $3"/lost+found" }' | sed 's://*:/:g' |
while read dir; do
	ignores="$(get_ignores)"
	if [ -z "$ignores" ]; then
		echo $dir
	else	
		for ignore in $ignores; do
			if is_subdir "$ignore" "$dir" ; then
				:
			else
				echo "$dir"
			fi
		done
	fi
done
