#!/bin/sh

set -e
. /usr/lib/cruft/common.sh
cruft_debug

cd /home/
for user in root `awk -F: '{ if ( 1000 <= $3 && $3 < 30000 ) print $1 }' /etc/passwd`; do
	home=`grep "^$user:" /etc/passwd | cut -d: -f6`

	if [ -d "$home" ]; then
		cruft_find "$home" -user $user
	fi

	[ -e /var/mail/$user ] && echo /var/mail/$user
done
