#!/bin/dash
set -e

# this is a trimmed down version of USERS script
# only usefull for cruft-ng
#
# cruft won't see this file

for user in root `awk -F: '{ if ( 1000 <= $3 && $3 < 30000 ) print $1 }' /etc/passwd`; do
	home=`grep "^$user:" /etc/passwd | cut -d: -f6`

	[ -d "$home" ] && echo $home
	[ -e /var/mail/$user ] && echo /var/mail/$user
	[ -e /var/spool/cron/crontabs/$user ] && echo /var/spool/cron/crontabs/$user
done
