#!/bin/sh -e
versions=$(/usr/sbin/dkms status -m virtualbox | cut -d\, -f 3 | tr -d ' ')
for ver in $versions
do
    echo /lib/modules/${ver}/updates
    echo /lib/modules/${ver}/updates/dkms
    echo /lib/modules/${ver}/updates/dkms/vboxdrv.ko
    echo /lib/modules/${ver}/updates/dkms/vboxnetadp.ko
    echo /lib/modules/${ver}/updates/dkms/vboxnetfit.ko
    echo /lib/modules/${ver}/updates/dkms/vboxpci.ko
done
