#!/bin/sh -e
ver=$(uname -r)
if [ -e /lib/modules/${ver}/updates/dkms/zfs.ko ]
then
    echo /lib/modules/${ver}/updates
    echo /lib/modules/${ver}/updates/dkms
    echo /lib/modules/${ver}/updates/dkms/zfs.ko
    echo /lib/modules/${ver}/updates/dkms/zcommon.ko
    echo /lib/modules/${ver}/updates/dkms/znvpair.ko
    echo /lib/modules/${ver}/updates/dkms/zpios.ko
    echo /lib/modules/${ver}/updates/dkms/zunicode.ko
fi
